/*
 * This file was automatically generated by SERP generator on 2026-06-12.
 */

#include "CarNavigationManager.hpp"

#include "ILocationHal.hpp"

#include <iomanip>
#include <sstream>

namespace Minivi
{
    std::shared_ptr<ICarNavigationManager> ICarNavigationManager::create(std::shared_ptr<ILocationHal> locationhal) {
        return std::make_shared<CarNavigationManager>(locationhal);
    }

    CarNavigationManager::CarNavigationManager(std::shared_ptr<ILocationHal> locationhal)
        : CarNavigationManagerBase(locationhal)
    {
        logMethod("CarNavigationManager");
        CurrentGuidanceState.assignFromTransport(GuidanceState::inactive);
        RouteActive.assignFromTransport(false);
        Destination.assignFromTransport(std::string{});
        Latitude.assignFromTransport(0.0);
        Longitude.assignFromTransport(0.0);
        Speed.assignFromTransport(0.0);
        Heading.assignFromTransport(0.0);
        DistanceToTarget.assignFromTransport(0.0);
    }

    CarNavigationManager::~CarNavigationManager() noexcept = default;

    void CarNavigationManager::onInit(const std::function<void(serp::Service::Status)> reply)
    {
        logInfo() << "onInit";
        CurrentGuidanceState = static_cast<GuidanceState>(CurrentGuidanceState);

        mPositionSubId = mLocationHal->PositionUpdated.connect([this](GpsPosition pos) {
            Latitude  = pos.latitude;
            Longitude = pos.longitude;
            Speed     = pos.speed;
            Heading   = pos.heading;
            PositionUpdated(pos);
        });

        reply(serp::Service::Status::SUCCESSFUL);
    }

    void CarNavigationManager::onDeinit(const std::function<void(serp::Service::Status)> reply)
    {
        logInfo() << "onDeinit";
        if (mPositionSubId) {
            mLocationHal->PositionUpdated.disconnect(mPositionSubId);
            mPositionSubId = 0;
        }
        reply(serp::Service::Status::SUCCESSFUL);
    }

    void CarNavigationManager::startRoute(serp::ResponsePtr<bool> reply, const std::string& destination)
    {
        logInfo() << "startRoute destination=" << destination;
        Destination          = destination;
        RouteActive          = true;
        CurrentGuidanceState = GuidanceState::active;
        GuidanceChanged(GuidanceState::active, destination);
        reply->call(true);
    }

    void CarNavigationManager::nextPrompt(serp::ResponsePtr<std::string> reply)
    {
        reply->call("Continue on current route");
    }

    void CarNavigationManager::cancelRoute(serp::ResponsePtr<bool> reply)
    {
        logInfo() << "cancelRoute";
        Destination          = "";
        RouteActive          = false;
        CurrentGuidanceState = GuidanceState::inactive;
        GuidanceChanged(GuidanceState::inactive, "");
        reply->call(true);
    }

    void CarNavigationManager::getGuidanceState(serp::ResponsePtr<GuidanceState> reply)
    {
        reply->call(static_cast<GuidanceState>(CurrentGuidanceState));
    }

    void CarNavigationManager::guidanceDestination(serp::ResponsePtr<std::string> reply)
    {
        reply->call(static_cast<std::string>(Destination));
    }

    void CarNavigationManager::frame(serp::ResponsePtr<std::string> reply)
    {
        std::ostringstream out;
        std::ostringstream ss;
        ss << static_cast<GuidanceState>(CurrentGuidanceState);
        out << "navigation.state="       << ss.str() << "\n";
        out << "navigation.destination=" << static_cast<std::string>(Destination) << "\n";
        out << std::fixed << std::setprecision(6);
        out << "location.latitude="  << static_cast<double>(Latitude)  << "\n";
        out << "location.longitude=" << static_cast<double>(Longitude) << "\n";
        out << std::setprecision(1);
        out << "location.speed="   << static_cast<double>(Speed)   << "\n";
        out << "location.heading=" << static_cast<double>(Heading) << "\n";
        reply->call(out.str());
    }

} // namespace Minivi
