/*
 * This file was automatically generated by SERP generator on 2026-06-12.
 */

#pragma once

#include <functional>
#include <memory>
#include <tuple>

#include "CarNavigationManagerBase.hpp"

namespace Minivi
{
    class CarNavigationManager : public CarNavigationManagerBase
    {
    public:
        explicit CarNavigationManager(std::shared_ptr<ILocationHal> locationhal);
        ~CarNavigationManager() noexcept override;

    protected:
        void onInit(const std::function<void(serp::Service::Status)> reply) override;
        void onDeinit(const std::function<void(serp::Service::Status)> reply) override;

        void startRoute(serp::ResponsePtr<bool> reply, const std::string& destination) override;
        void nextPrompt(serp::ResponsePtr<std::string> reply) override;
        void cancelRoute(serp::ResponsePtr<bool> reply) override;
        void getGuidanceState(serp::ResponsePtr<GuidanceState> reply) override;
        void guidanceDestination(serp::ResponsePtr<std::string> reply) override;
        void frame(serp::ResponsePtr<std::string> reply) override;

    private:
        uint32_t mPositionSubId{0};
    };

} // namespace Minivi
