/*
 * This file was automatically generated by SERP generator on 2026-06-12.
 */

#pragma once

#include <functional>
#include <memory>
#include <string>
#include <tuple>
#include <vector>

#include "CarUserManagerBase.hpp"

namespace Minivi
{
    class CarUserManager : public CarUserManagerBase
    {
    public:
        explicit CarUserManager(std::shared_ptr<IPersistenceService> persistenceservice);
        ~CarUserManager() noexcept override;

    protected:
        void onInit(const std::function<void(serp::Service::Status)> reply) override;
        void onDeinit(const std::function<void(serp::Service::Status)> reply) override;

        void setTheme(serp::ResponsePtr<bool> reply, const std::string& theme) override;
        void setUnits(serp::ResponsePtr<bool> reply, const std::string& units) override;
        void setBrightness(serp::ResponsePtr<bool> reply, const int32_t& level) override;
        void setLanguage(serp::ResponsePtr<bool> reply, const std::string& lang) override;
        void loadProfile(serp::ResponsePtr<bool> reply, const std::string& user) override;
        void switchSeat(serp::ResponsePtr<bool> reply, const std::string& seat) override;
        void frame(serp::ResponsePtr<std::string> reply) override;
    };

} // namespace Minivi
