/*
 * This file was automatically generated by SERP generator on 2026-06-12.
 */

#include "CarUserManager.hpp"

#include <sstream>

namespace Minivi
{
    std::shared_ptr<ICarUserManager> ICarUserManager::create(std::shared_ptr<IPersistenceService> persistenceservice) {
        return std::make_shared<CarUserManager>(persistenceservice);
    }

    CarUserManager::CarUserManager(std::shared_ptr<IPersistenceService> persistenceservice)
        : CarUserManagerBase(persistenceservice)
    {
        logMethod("CarUserManager");
        Theme.assignFromTransport(Minivi::UserTheme::dark);
        Units.assignFromTransport(Minivi::UserUnits::metric);
        Brightness.assignFromTransport(80);
        Language.assignFromTransport(std::string{"en"});
        CurrentUser.assignFromTransport(std::string{"Driver"});
        ActiveSeat.assignFromTransport(std::string{"driver"});
        UserList.assignFromTransport(std::vector<std::string>{"Driver", "Passenger", "Guest"});
    }

    CarUserManager::~CarUserManager() noexcept = default;

    void CarUserManager::onInit(const std::function<void(serp::Service::Status)> reply)
    {
        logInfo() << "onInit";
        Theme      = static_cast<Minivi::UserTheme>(Theme);
        Units      = static_cast<Minivi::UserUnits>(Units);
        Brightness = static_cast<int32_t>(Brightness);
        Language   = static_cast<std::string>(Language);
        CurrentUser = static_cast<std::string>(CurrentUser);
        ActiveSeat  = static_cast<std::string>(ActiveSeat);
        UserList    = static_cast<std::vector<std::string>>(UserList);
        reply(serp::Service::Status::SUCCESSFUL);
    }

    void CarUserManager::onDeinit(const std::function<void(serp::Service::Status)> reply)
    {
        logInfo() << "onDeinit";
        reply(serp::Service::Status::SUCCESSFUL);
    }

    void CarUserManager::setTheme(serp::ResponsePtr<bool> reply, const Minivi::UserTheme& theme)
    {
        logInfo() << "setTheme theme=" << static_cast<int>(theme);
        Theme = theme;
        SettingChanged("theme", serp::toString(theme));
        reply->call(true);
    }

    void CarUserManager::setUnits(serp::ResponsePtr<bool> reply, const Minivi::UserUnits& units)
    {
        logInfo() << "setUnits units=" << static_cast<int>(units);
        Units = units;
        SettingChanged("units", serp::toString(units));
        reply->call(true);
    }

    void CarUserManager::setBrightness(serp::ResponsePtr<bool> reply, const int32_t& level)
    {
        logInfo() << "setBrightness level=" << level;
        Brightness = level;
        SettingChanged("brightness", std::to_string(level));
        reply->call(true);
    }

    void CarUserManager::setLanguage(serp::ResponsePtr<bool> reply, const std::string& lang)
    {
        logInfo() << "setLanguage lang=" << lang;
        Language = lang;
        SettingChanged("language", lang);
        reply->call(true);
    }

    void CarUserManager::loadProfile(serp::ResponsePtr<bool> reply, const std::string& user)
    {
        logInfo() << "loadProfile user=" << user;
        CurrentUser = user;
        ProfileChanged(user, 100);
        reply->call(true);
    }

    void CarUserManager::switchSeat(serp::ResponsePtr<bool> reply, const std::string& seat)
    {
        logInfo() << "switchSeat seat=" << seat;
        ActiveSeat = seat;
        reply->call(true);
    }

    void CarUserManager::frame(serp::ResponsePtr<std::string> reply)
    {
        std::ostringstream out;
        out << "user.current="    << static_cast<std::string>(CurrentUser) << "\n";
        out << "user.seat="       << static_cast<std::string>(ActiveSeat)  << "\n";
        out << "settings.theme="  << Theme       << "\n";
        out << "settings.units="  << Units       << "\n";
        out << "settings.brightness=" << static_cast<int32_t>(Brightness)  << "\n";
        out << "settings.language=" << static_cast<std::string>(Language)  << "\n";
        reply->call(out.str());
    }

} // namespace Minivi
