/*
 * This file was automatically generated by SERP generator on 2026-06-12.
 */

#pragma once

#include <algorithm>
#include <functional>
#include <map>
#include <memory>
#include <random>
#include <string>
#include <sys/types.h>
#include <tuple>
#include <vector>

#include "CarMediaManagerBase.hpp"

namespace Minivi
{
    class CarMediaManager : public CarMediaManagerBase
    {
    public:
        explicit CarMediaManager(std::shared_ptr<ICarAudioManager> caraudiomanager);
        ~CarMediaManager() noexcept override;

    protected:
        void onInit(const std::function<void(serp::Service::Status)> reply) override;
        void onDeinit(const std::function<void(serp::Service::Status)> reply) override;

        void play(serp::ResponsePtr<bool> reply, const std::string& source) override;
        void pause(serp::ResponsePtr<bool> reply) override;
        void next(serp::ResponsePtr<bool> reply) override;
        void previous(serp::ResponsePtr<bool> reply) override;
        void playAt(serp::ResponsePtr<bool> reply, const int32_t& index) override;
        void getTrackList(serp::ResponsePtr<std::vector<TrackInfo>> reply) override;
        void seekTo(serp::ResponsePtr<bool> reply, const int32_t& positionMs) override;
        void setShuffleEnabled(serp::ResponsePtr<bool> reply, const bool& enabled) override;
        void setRepeatMode(serp::ResponsePtr<bool> reply, const RepeatMode& mode) override;
        void onFocusEvent(serp::ResponsePtr<bool> reply, const std::string& event) override;
        void recent(serp::ResponsePtr<std::vector<TrackInfo>> reply) override;
        void sourceHistory(serp::ResponsePtr<std::map<std::string, TrackInfo>> reply) override;
        void getPlaybackState(serp::ResponsePtr<PlaybackState> reply) override;
        void playbackSource(serp::ResponsePtr<std::string> reply) override;
        void playbackTrack(serp::ResponsePtr<std::optional<TrackInfo>> reply) override;
        void frame(serp::ResponsePtr<std::string> reply) override;
        void debugEcho(serp::ResponsePtr<std::string> reply, const std::string& text) override;
        void debugMix(serp::ResponsePtr<DebugSample> reply, const bool& flag, const uint32_t& count, const float& ratio) override;
        void debugList(serp::ResponsePtr<std::vector<std::string>> reply, const std::string& seed) override;
        void debugLookup(serp::ResponsePtr<std::map<std::string, uint32_t>> reply, const std::string& key) override;

    private:
        void scanPlaylist(const std::string& dir);
        void playTrack(int index, int32_t startPositionMs = 0);
        void stopPlayback();
        void onPlaybackTick();
        int  nextIndex();
        int  prevIndex();
        void rebuildShuffleOrder();
        TrackInfo probeTrack(const std::string& path) const;

        std::vector<std::string>         mPlaylist;
        int                              mCurrentIndex{0};
        pid_t                            mPlayPid{-1};
        serp::TimerPtr                   mPlayTimer;
        std::map<std::string, TrackInfo> mTrackCache;

        // shuffle support
        std::vector<int>                 mShuffleOrder;
        int                              mShufflePos{0};
        std::mt19937                     mRng{std::random_device{}()};
    };

} // namespace Minivi
