/*
 * This file was automatically generated by SERP generator on 2026-06-12.
 */

#include "CarMediaManager.hpp"

#include <algorithm>
#include <array>
#include <chrono>
#include <csignal>
#include <cstdio>
#include <dirent.h>
#include <fcntl.h>
#include <map>
#include <numeric>
#include <sstream>
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <unistd.h>
#include <vector>

namespace Minivi
{

namespace {

static const std::vector<std::string> kAudioExts = {".mp3", ".flac", ".ogg", ".oga", ".wav", ".m4a", ".aac", ".aiff", ".aif"};

static const std::map<std::string, std::pair<std::string, std::string>> kBundledTrackMeta = {
    {"track_01", {"Groove Salad",    "SomaFM / Demo"}},
    {"track_02", {"Secret Agent",    "SomaFM / Demo"}},
    {"track_03", {"Indie Pop Rocks", "SomaFM / Demo"}},
    {"track_04", {"Beat Blender",    "SomaFM / Demo"}},
    {"track_05", {"Mission Control", "SomaFM / Demo"}},
};

std::vector<std::string> buildSearchDirs()
{
    std::vector<std::string> dirs;
    if (const char* root = std::getenv("SERP_PRODUCT_ROOT"))
        dirs.push_back(std::string(root) + "/assets/media");
    return dirs;
}

bool hasAudioExt(const std::string& name)
{
    std::string lower = name;
    std::transform(lower.begin(), lower.end(), lower.begin(), ::tolower);
    for (const auto& ext : kAudioExts)
        if (lower.size() >= ext.size() &&
            lower.compare(lower.size() - ext.size(), ext.size(), ext) == 0)
            return true;
    return false;
}

std::string baseName(const std::string& path)
{
    const auto pos = path.rfind('/');
    return pos == std::string::npos ? path : path.substr(pos + 1);
}

std::string stripExt(const std::string& name)
{
    const auto pos = name.rfind('.');
    return pos == std::string::npos ? name : name.substr(0, pos);
}

bool commandOnPath(const char* cmd)
{
    const char* path_env = std::getenv("PATH");
    if (!path_env) return false;
    std::istringstream ss(path_env);
    std::string dir;
    while (std::getline(ss, dir, ':')) {
        if (dir.empty()) continue;
        if (access((dir + "/" + cmd).c_str(), X_OK) == 0) return true;
    }
    return false;
}

const bool kHasFfplay = commandOnPath("ffplay");

} // namespace

    std::shared_ptr<ICarMediaManager> ICarMediaManager::create(std::shared_ptr<ICarAudioManager> caraudiomanager) {
        return std::make_shared<CarMediaManager>(caraudiomanager);
    }

    CarMediaManager::CarMediaManager(std::shared_ptr<ICarAudioManager> caraudiomanager)
        : CarMediaManagerBase(caraudiomanager)
    {
        logMethod("CarMediaManager");
        CurrentPlaybackState.assignFromTransport(PlaybackState::stopped);
        ShuffleEnabled.assignFromTransport(false);
        CurrentRepeatMode.assignFromTransport(Minivi::RepeatMode::off);
        DebugEnabled.assignFromTransport(true);
        CurrentDebugLevel.assignFromTransport(Minivi::DebugLevel::basic);
        DebugCounter.assignFromTransport(0);
        DebugTemperature.assignFromTransport(21.5f);
        CurrentDebugSample.assignFromTransport(Minivi::DebugSample{"initial", 0, true});
        DebugTags.assignFromTransport(std::vector<std::string>{"media", "debug", "test"});
        DebugOptionalNote.assignFromTransport(std::optional<std::string>{"ready"});
    }

    CarMediaManager::~CarMediaManager() noexcept
    {
        stopPlayback();
    }

    void CarMediaManager::onInit(const std::function<void(serp::Service::Status)> reply)
    {
        logInfo() << "onInit";
        CurrentPlaybackState = static_cast<PlaybackState>(CurrentPlaybackState);

        for (const auto& dir : buildSearchDirs())
            scanPlaylist(dir);

        logInfo() << "found " << mPlaylist.size() << " tracks";
        PlaylistSize = static_cast<uint32_t>(mPlaylist.size());
        TrackIndex   = mCurrentIndex;

        // Probe all tracks for metadata and publish the full list
        std::vector<TrackInfo> list;
        list.reserve(mPlaylist.size());
        for (const auto& path : mPlaylist) {
            const TrackInfo info = probeTrack(path);
            mTrackCache[path] = info;
            list.push_back(info);
        }
        TrackList = list;

        rebuildShuffleOrder();

        reply(serp::Service::Status::SUCCESSFUL);
    }

    void CarMediaManager::onDeinit(const std::function<void(serp::Service::Status)> reply)
    {
        logInfo() << "onDeinit";
        stopPlayback();
        if (mPlayTimer) { mPlayTimer->stop(); mPlayTimer.reset(); }
        reply(serp::Service::Status::SUCCESSFUL);
    }

    void CarMediaManager::scanPlaylist(const std::string& dir)
    {
        DIR* d = opendir(dir.c_str());
        if (!d) return;
        struct dirent* ent;
        while ((ent = readdir(d)) != nullptr) {
            const std::string name(ent->d_name);
            if (name.empty() || name[0] == '.') continue;
            const std::string path = dir + "/" + name;
            struct stat st;
            if (stat(path.c_str(), &st) != 0) continue;
            if (S_ISREG(st.st_mode) && hasAudioExt(name))
                mPlaylist.push_back(path);
        }
        closedir(d);
        std::sort(mPlaylist.begin(), mPlaylist.end());
    }

    TrackInfo CarMediaManager::probeTrack(const std::string& path) const
    {
        const auto it = mTrackCache.find(path);
        if (it != mTrackCache.end()) return it->second;

        TrackInfo info{};
        const std::string stem = stripExt(baseName(path));
        const auto meta = kBundledTrackMeta.find(stem);
        if (meta != kBundledTrackMeta.end()) {
            info.title  = meta->second.first;
            info.artist = meta->second.second;
        } else {
            info.title  = stem;
            info.artist = "Unknown";
        }
        info.duration = 0;

        std::array<char, 512> buf;
#ifdef __APPLE__
        const std::string cmd = "afinfo \"" + path + "\" 2>/dev/null";
        FILE* fp = popen(cmd.c_str(), "r");
        if (fp) {
            while (fgets(buf.data(), buf.size(), fp)) {
                const std::string line(buf.data());
                // "estimated duration: 123.456000 sec"
                const auto pos = line.find("estimated duration: ");
                if (pos != std::string::npos) {
                    try {
                        info.duration = static_cast<uint32_t>(
                            std::stof(line.substr(pos + 20)) * 1000.0f);
                    } catch (...) {}
                    break;
                }
            }
            pclose(fp);
        }
#else
        const std::string cmd = "ffprobe -v error -show_entries format=duration"
                                " -of default=noprint_wrappers=1:nokey=1 \"" + path + "\" 2>/dev/null";
        FILE* fp = popen(cmd.c_str(), "r");
        if (fp) {
            if (fgets(buf.data(), buf.size(), fp))
                info.duration = static_cast<uint32_t>(std::stof(buf.data()) * 1000.0f);
            pclose(fp);
        }
#endif
        return info;
    }

    void CarMediaManager::rebuildShuffleOrder()
    {
        mShuffleOrder.resize(mPlaylist.size());
        std::iota(mShuffleOrder.begin(), mShuffleOrder.end(), 0);
        std::shuffle(mShuffleOrder.begin(), mShuffleOrder.end(), mRng);
        // put current track first in the shuffled order
        auto it = std::find(mShuffleOrder.begin(), mShuffleOrder.end(), mCurrentIndex);
        if (it != mShuffleOrder.end())
            std::iter_swap(mShuffleOrder.begin(), it);
        mShufflePos = 0;
    }

    int CarMediaManager::nextIndex()
    {
        const bool shuffle = static_cast<bool>(ShuffleEnabled);
        const auto repeat  = static_cast<Minivi::RepeatMode>(CurrentRepeatMode);
        const int  n       = static_cast<int>(mPlaylist.size());
        if (n == 0) return 0;

        if (repeat == Minivi::RepeatMode::repeatOne)
            return mCurrentIndex;

        if (shuffle) {
            const int nextPos = mShufflePos + 1;
            if (nextPos >= n) return mShuffleOrder[0]; // wrap
            return mShuffleOrder[nextPos];
        }

        // sequential
        const int next = mCurrentIndex + 1;
        if (next >= n)
            return (repeat == Minivi::RepeatMode::repeatAll) ? 0 : -1;
        return next;
    }

    int CarMediaManager::prevIndex()
    {
        const int n = static_cast<int>(mPlaylist.size());
        if (n == 0) return 0;
        const int prev = mCurrentIndex - 1;
        return prev < 0 ? n - 1 : prev;
    }

    void CarMediaManager::playTrack(int index, int32_t startPositionMs)
    {
        stopPlayback();
        if (mPlaylist.empty()) {
            CurrentPlaybackState = PlaybackState::stopped;
            PlaybackChanged(PlaybackState::stopped, std::nullopt);
            return;
        }
        const int n = static_cast<int>(mPlaylist.size());
        mCurrentIndex = ((index % n) + n) % n;

        // update shuffle position if shuffle is on
        if (static_cast<bool>(ShuffleEnabled)) {
            auto it = std::find(mShuffleOrder.begin(), mShuffleOrder.end(), mCurrentIndex);
            if (it != mShuffleOrder.end())
                mShufflePos = static_cast<int>(std::distance(mShuffleOrder.begin(), it));
        }

        TrackIndex = mCurrentIndex;
        const std::string& path = mPlaylist[mCurrentIndex];

        const TrackInfo info = probeTrack(path);
        const_cast<std::map<std::string, TrackInfo>&>(mTrackCache)[path] = info;

        // If seeking but ffplay is unavailable, reset to 0 so position display stays honest
        const int32_t effectiveStart = (startPositionMs > 0 && !kHasFfplay) ? 0 : startPositionMs;
        logInfo() << "playTrack [" << mCurrentIndex << "] " << info.title
                  << (effectiveStart > 0 ? " @" + std::to_string(effectiveStart) + "ms" : "")
                  << (startPositionMs > 0 && !kHasFfplay ? " (ffplay unavailable, starting from 0)" : "");
        CurrentPositionMs = effectiveStart;

        const pid_t pid = fork();
        if (pid < 0) {
            CurrentPlaybackState = PlaybackState::stopped;
            PlaybackChanged(PlaybackState::stopped, std::nullopt);
            return;
        }
        if (pid == 0) {
            const int fd = open("/dev/null", O_WRONLY);
            if (fd >= 0) { dup2(fd, STDOUT_FILENO); dup2(fd, STDERR_FILENO); close(fd); }
            if (effectiveStart > 0) {
                const std::string ss = std::to_string(effectiveStart / 1000.0);
                execlp("ffplay", "ffplay", "-nodisp", "-loglevel", "quiet",
                       "-autoexit", "-ss", ss.c_str(), path.c_str(), nullptr);
                _exit(1);  // ffplay failed (shouldn't reach here since kHasFfplay == true)
            }
            execlp("afplay", "afplay", path.c_str(), nullptr);
            execlp("ffplay", "ffplay", "-nodisp", "-loglevel", "quiet",
                   "-autoexit", path.c_str(), nullptr);
            _exit(1);
        }
        mPlayPid = pid;
        CurrentPlaybackState = PlaybackState::playing;
        CurrentTrack = info;
        PlaybackChanged(PlaybackState::playing, info);

        mPlayTimer = serp::Timer::create(std::chrono::milliseconds{1000}, true, [this](serp::TimerPtr) {
            onPlaybackTick();
        });
        mPlayTimer->start();
    }

    void CarMediaManager::stopPlayback()
    {
        if (mPlayTimer) { mPlayTimer->stop(); mPlayTimer.reset(); }
        if (mPlayPid > 0) {
            kill(mPlayPid, SIGKILL);
            waitpid(mPlayPid, nullptr, 0);  // block until child actually exits
            mPlayPid = -1;
        }
    }

    void CarMediaManager::onPlaybackTick()
    {
        if (mPlayPid <= 0) return;
        if (static_cast<PlaybackState>(CurrentPlaybackState) == PlaybackState::paused) return;
        CurrentPositionMs = static_cast<int32_t>(CurrentPositionMs) + 1000;
        int status = 0;
        const pid_t result = waitpid(mPlayPid, &status, WNOHANG);
        if (result == mPlayPid) {
            mPlayPid = -1;
            if (mPlayTimer) { mPlayTimer->stop(); mPlayTimer.reset(); }
            logInfo() << "track ended, advancing";
            const int next = nextIndex();
            if (next < 0) {
                // end of playlist, normal mode
                CurrentPlaybackState = PlaybackState::stopped;
                PlaybackChanged(PlaybackState::stopped, std::nullopt);
            } else {
                playTrack(next);
            }
        }
    }

    void CarMediaManager::play(serp::ResponsePtr<bool> reply, const std::string& source)
    {
        logInfo() << "play source=" << source;

        if (source.size() > 6 && source.compare(0, 6, "track:") == 0) {
            try { playTrack(std::stoi(source.substr(6))); }
            catch (...) { playTrack(mCurrentIndex); }
            reply->call(true);
            return;
        }

        if (!source.empty())
            CurrentPlaybackSource = source;

        if (static_cast<PlaybackState>(CurrentPlaybackState) == PlaybackState::paused && mPlayPid > 0) {
            kill(mPlayPid, SIGCONT);
            CurrentPlaybackState = PlaybackState::playing;
            PlaybackChanged(PlaybackState::playing, static_cast<std::optional<TrackInfo>>(CurrentTrack));
        } else {
            playTrack(mCurrentIndex);
        }
        reply->call(true);
    }

    void CarMediaManager::pause(serp::ResponsePtr<bool> reply)
    {
        logInfo() << "pause";
        if (mPlayPid > 0)
            kill(mPlayPid, SIGSTOP);
        CurrentPlaybackState = PlaybackState::paused;
        PlaybackChanged(PlaybackState::paused, static_cast<std::optional<TrackInfo>>(CurrentTrack));
        reply->call(true);
    }

    void CarMediaManager::next(serp::ResponsePtr<bool> reply)
    {
        logInfo() << "next";
        const int next = nextIndex();
        playTrack(next >= 0 ? next : 0);
        reply->call(true);
    }

    void CarMediaManager::previous(serp::ResponsePtr<bool> reply)
    {
        logInfo() << "previous";
        playTrack(prevIndex());
        reply->call(true);
    }

    void CarMediaManager::playAt(serp::ResponsePtr<bool> reply, const int32_t& index)
    {
        logInfo() << "playAt index=" << index;
        playTrack(static_cast<int>(index));
        reply->call(true);
    }

    void CarMediaManager::getTrackList(serp::ResponsePtr<std::vector<TrackInfo>> reply)
    {
        std::vector<TrackInfo> list;
        list.reserve(mPlaylist.size());
        for (const auto& path : mPlaylist)
            list.push_back(probeTrack(path));
        reply->call(list);
    }

    void CarMediaManager::seekTo(serp::ResponsePtr<bool> reply, const int32_t& positionMs)
    {
        logInfo() << "seekTo positionMs=" << positionMs;
        if (mPlaylist.empty() || static_cast<PlaybackState>(CurrentPlaybackState) == PlaybackState::stopped) {
            reply->call(false);
            return;
        }
        playTrack(mCurrentIndex, positionMs);
        reply->call(true);
    }

    void CarMediaManager::setShuffleEnabled(serp::ResponsePtr<bool> reply, const bool& enabled)
    {
        logInfo() << "setShuffleEnabled enabled=" << enabled;
        ShuffleEnabled = enabled;
        if (enabled)
            rebuildShuffleOrder();
        reply->call(true);
    }

    void CarMediaManager::setRepeatMode(serp::ResponsePtr<bool> reply, const Minivi::RepeatMode& mode)
    {
        logInfo() << "setRepeatMode";
        CurrentRepeatMode = mode;
        reply->call(true);
    }

    void CarMediaManager::onFocusEvent(serp::ResponsePtr<bool> reply, const std::string& event)
    {
        logInfo() << "onFocusEvent event=" << event;
        if (event == "lost") {
            if (static_cast<PlaybackState>(CurrentPlaybackState) == PlaybackState::playing) {
                if (mPlayPid > 0) kill(mPlayPid, SIGSTOP);
                CurrentPlaybackState = PlaybackState::paused;
                PlaybackChanged(PlaybackState::paused, static_cast<std::optional<TrackInfo>>(CurrentTrack));
            }
        } else if (event == "gained") {
            if (static_cast<PlaybackState>(CurrentPlaybackState) == PlaybackState::paused && mPlayPid > 0) {
                kill(mPlayPid, SIGCONT);
                CurrentPlaybackState = PlaybackState::playing;
                PlaybackChanged(PlaybackState::playing, static_cast<std::optional<TrackInfo>>(CurrentTrack));
            }
        }
        reply->call(true);
    }

    void CarMediaManager::recent(serp::ResponsePtr<std::vector<TrackInfo>> reply)
    {
        std::vector<TrackInfo> result;
        result.reserve(mTrackCache.size());
        for (const auto& [_, info] : mTrackCache)
            result.push_back(info);
        reply->call(result);
    }

    void CarMediaManager::sourceHistory(serp::ResponsePtr<std::map<std::string, TrackInfo>> reply)
    {
        reply->call(mTrackCache);
    }

    void CarMediaManager::getPlaybackState(serp::ResponsePtr<PlaybackState> reply)
    {
        reply->call(static_cast<PlaybackState>(CurrentPlaybackState));
    }

    void CarMediaManager::playbackSource(serp::ResponsePtr<std::string> reply)
    {
        reply->call(static_cast<std::string>(CurrentPlaybackSource));
    }

    void CarMediaManager::playbackTrack(serp::ResponsePtr<std::optional<TrackInfo>> reply)
    {
        reply->call(static_cast<std::optional<TrackInfo>>(CurrentTrack));
    }

    void CarMediaManager::frame(serp::ResponsePtr<std::string> reply)
    {
        std::ostringstream out;
        std::ostringstream ss;
        ss << static_cast<PlaybackState>(CurrentPlaybackState);
        out << "media.state="        << ss.str() << "\n";
        out << "media.source="       << static_cast<std::string>(CurrentPlaybackSource) << "\n";
        const auto track = static_cast<std::optional<TrackInfo>>(CurrentTrack);
        if (track) {
            out << "media.track="   << track->title  << "\n";
            out << "media.artist="  << track->artist << "\n";
        }
        out << "media.playlist_size=" << mPlaylist.size() << "\n";
        out << "media.track_index="   << mCurrentIndex    << "\n";
        reply->call(out.str());
    }

    void CarMediaManager::debugEcho(serp::ResponsePtr<std::string> reply, const std::string& text)
    {
        DebugCounter = static_cast<uint32_t>(DebugCounter) + 1;
        DebugMessage(static_cast<DebugLevel>(CurrentDebugLevel), "echo:" + text);
        reply->call(text);
    }

    void CarMediaManager::debugMix(serp::ResponsePtr<DebugSample> reply, const bool& flag, const uint32_t& count, const float& ratio)
    {
        const auto sample = DebugSample{
            flag ? "enabled" : "disabled",
            static_cast<uint32_t>(count + static_cast<uint32_t>(ratio * 10.0f)),
            flag
        };
        DebugEnabled = flag;
        DebugCounter = sample.count;
        DebugTemperature = ratio;
        CurrentDebugSample = sample;
        DebugTick(sample.count, sample);
        reply->call(sample);
    }

    void CarMediaManager::debugList(serp::ResponsePtr<std::vector<std::string>> reply, const std::string& seed)
    {
        const std::vector<std::string> values{seed, seed + "-one", seed + "-two"};
        DebugTags = values;
        reply->call(values);
    }

    void CarMediaManager::debugLookup(serp::ResponsePtr<std::map<std::string, uint32_t>> reply, const std::string& key)
    {
        reply->call({
            {key, static_cast<uint32_t>(key.size())},
            {"counter", static_cast<uint32_t>(DebugCounter)},
            {"playlist", static_cast<uint32_t>(mPlaylist.size())}
        });
    }

} // namespace Minivi
