/*
 * This file was automatically generated by SERP generator on 2026-06-12.
 */

#include "CarAudioManager.hpp"

#include <sstream>

namespace Minivi
{
    std::shared_ptr<ICarAudioManager> ICarAudioManager::create(std::shared_ptr<IAudioHal> audiohal) {
        return std::make_shared<CarAudioManager>(audiohal);
    }

    CarAudioManager::CarAudioManager(std::shared_ptr<IAudioHal> audiohal)
        : CarAudioManagerBase(audiohal)
    {
        logMethod("CarAudioManager");
    }

    CarAudioManager::~CarAudioManager() noexcept = default;

    void CarAudioManager::onInit(const std::function<void(serp::Service::Status)> reply)
    {
        logInfo() << "onInit";
        reply(serp::Service::Status::SUCCESSFUL);
    }

    void CarAudioManager::onDeinit(const std::function<void(serp::Service::Status)> reply)
    {
        logInfo() << "onDeinit";
        reply(serp::Service::Status::SUCCESSFUL);
    }

    void CarAudioManager::requestFocus(serp::ResponsePtr<FocusDecision> reply, const std::string& owner, const int32_t& priority, const FocusMode& mode)
    {
        logInfo() << "requestFocus owner=" << owner << " priority=" << priority;
        ActiveFocusOwner = owner;
        ActiveFocusMode  = mode;
        FocusChanged(owner, mode, FocusDecision::granted);
        reply->call(FocusDecision::granted);
    }

    void CarAudioManager::releaseFocus(serp::ResponsePtr<bool> reply, const std::string& owner)
    {
        logInfo() << "releaseFocus owner=" << owner;
        if (static_cast<std::string>(ActiveFocusOwner) == owner) {
            ActiveFocusOwner = "";
            ActiveFocusMode  = FocusMode::none;
            FocusChanged("", FocusMode::none, FocusDecision::released);
        }
        reply->call(true);
    }

    void CarAudioManager::focusOwner(serp::ResponsePtr<std::string> reply)
    {
        reply->call(static_cast<std::string>(ActiveFocusOwner));
    }

    void CarAudioManager::getFocusMode(serp::ResponsePtr<FocusMode> reply)
    {
        reply->call(static_cast<FocusMode>(ActiveFocusMode));
    }

    void CarAudioManager::frame(serp::ResponsePtr<std::string> reply)
    {
        std::ostringstream out;
        out << "audio.focus.owner=" << static_cast<std::string>(ActiveFocusOwner) << "\n";
        out << "audio.focus.mode="  << ActiveFocusMode << "\n";
        reply->call(out.str());
    }

} // namespace Minivi
