/*
 * This file was automatically generated by SERP generator on 2026-06-12.
 */

#pragma once

#include <functional>
#include <memory>
#include <tuple>

#include "CarAudioManagerBase.hpp"

namespace Minivi
{
    class CarAudioManager : public CarAudioManagerBase
    {
    public:
        explicit CarAudioManager(std::shared_ptr<IAudioHal> audiohal);
        ~CarAudioManager() noexcept override;

    protected:
        void onInit(const std::function<void(serp::Service::Status)> reply) override;
        void onDeinit(const std::function<void(serp::Service::Status)> reply) override;

        void requestFocus(serp::ResponsePtr<std::string> reply, const std::string& owner, const int32_t& priority, const std::string& mode) override;
        void releaseFocus(serp::ResponsePtr<bool> reply, const std::string& owner) override;
        void focusOwner(serp::ResponsePtr<std::string> reply) override;
        void focusMode(serp::ResponsePtr<std::string> reply) override;
        void frame(serp::ResponsePtr<std::string> reply) override;
    };

} // namespace Minivi
