/*
 * This file was automatically generated by SERP generator on 2026-06-12.
 */

#include "CarPowerManager.hpp"

#include "ICarPropertyService.hpp"

#include <sstream>

namespace Minivi
{
    std::shared_ptr<ICarPowerManager> ICarPowerManager::create(std::shared_ptr<ICarPropertyService> carpropertyservice) {
        return std::make_shared<CarPowerManager>(carpropertyservice);
    }

    CarPowerManager::CarPowerManager(std::shared_ptr<ICarPropertyService> carpropertyservice)
        : CarPowerManagerBase(carpropertyservice)
    {
        logMethod("CarPowerManager");
        CurrentPowerState.assignFromTransport(PowerState::off);
    }

    CarPowerManager::~CarPowerManager() noexcept = default;

    void CarPowerManager::onInit(const std::function<void(serp::Service::Status)> reply)
    {
        logInfo() << "onInit";
        CurrentPowerState = static_cast<PowerState>(CurrentPowerState);
        reply(serp::Service::Status::SUCCESSFUL);
    }

    void CarPowerManager::onDeinit(const std::function<void(serp::Service::Status)> reply)
    {
        logInfo() << "onDeinit";
        reply(serp::Service::Status::SUCCESSFUL);
    }

    void CarPowerManager::requestState(serp::ResponsePtr<bool> reply, const PowerState& state)
    {
        logInfo() << "requestState state=" << state;
        CurrentPowerState = state;
        PowerStateChanged(state);

        // Mirror ignition state into vehicle property store
        if (mCarPropertyService) {
            const std::string ignition = (state == PowerState::on) ? "on" : "off";
            mCarPropertyService->SetProperty("ignition", ignition);
        }

        reply->call(true);
    }

    void CarPowerManager::getPowerState(serp::ResponsePtr<PowerState> reply)
    {
        reply->call(static_cast<PowerState>(CurrentPowerState));
    }

} // namespace Minivi
