/*
 * This file was automatically generated by SERP generator on 2026-06-12.
 */

#pragma once

#include <functional>
#include <memory>
#include <tuple>

#include "CarPowerManagerBase.hpp"

namespace Minivi
{
    class CarPowerManager : public CarPowerManagerBase
    {
    public:
        explicit CarPowerManager(std::shared_ptr<ICarPropertyService> carpropertyservice);
        ~CarPowerManager() noexcept override;

    protected:
        void onInit(const std::function<void(serp::Service::Status)> reply) override;
        void onDeinit(const std::function<void(serp::Service::Status)> reply) override;

        void requestState(serp::ResponsePtr<bool> reply, const PowerState& state) override;
        void getPowerState(serp::ResponsePtr<PowerState> reply) override;
    };

} // namespace Minivi
