/*
 * This file was automatically generated by SERP generator on 2026-06-12.
 */

#pragma once

#include <functional>
#include <memory>
#include <tuple>

#include "HmiAppBase.hpp"
#include "ICarRadioManager.hpp"
#include "ICarMediaManager.hpp"
#include "ICarClimateManager.hpp"
#include "ICarNavigationManager.hpp"
#include "ICarPhoneManager.hpp"
#include "ICarPropertyService.hpp"
#include "ICarUserManager.hpp"
#include "ICarNotificationManager.hpp"

namespace Minivi
{
    class HmiApp : public HmiAppBase
    {
    public:
        explicit HmiApp(std::shared_ptr<ICarRadioManager> radio,
                        std::shared_ptr<ICarMediaManager> media,
                        std::shared_ptr<ICarClimateManager> climate,
                        std::shared_ptr<ICarNavigationManager> navigation,
                        std::shared_ptr<ICarPhoneManager> phone,
                        std::shared_ptr<ICarPropertyService> vehicle,
                        std::shared_ptr<ICarUserManager> user,
                        std::shared_ptr<ICarNotificationManager> notifications);
        ~HmiApp() noexcept override;

    protected:
        void onInit(const std::function<void(serp::Service::Status)> reply) override;
        void onDeinit(const std::function<void(serp::Service::Status)> reply) override;


    };

} // namespace Minivi
