/*
 * This file was automatically generated by SERP generator on 2026-06-12.
 */

#include "HmiApp.hpp"

namespace Minivi
{
    HmiApp::HmiApp(std::shared_ptr<ICarRadioManager> radio,
                   std::shared_ptr<ICarMediaManager> media,
                   std::shared_ptr<ICarClimateManager> climate,
                   std::shared_ptr<ICarNavigationManager> navigation,
                   std::shared_ptr<ICarCallManager> call,
                   std::shared_ptr<ICarContactsManager> contacts,
                   std::shared_ptr<ICarPropertyService> vehicle,
                   std::shared_ptr<ICarUserManager> user,
                   std::shared_ptr<ICarNotificationManager> notifications)
        : HmiAppBase(radio, media, climate, navigation, call, contacts, vehicle, user, notifications)
    {
        logMethod("HmiApp");
    }

    HmiApp::~HmiApp() noexcept = default;

    void HmiApp::onInit(const std::function<void(serp::Service::Status)> reply)
    {
        logInfo() << "onInit";
        reply(serp::Service::Status::SUCCESSFUL);
    }

    void HmiApp::onDeinit(const std::function<void(serp::Service::Status)> reply)
    {
        logInfo() << "onDeinit";
        reply(serp::Service::Status::SUCCESSFUL);
    }

} // namespace Minivi
