/*
 * This file was automatically generated by SERP generator on 2026-06-23.
 */

#pragma once

#include <functional>
#include <memory>
#include <tuple>

#include "CarCallManagerBase.hpp"

namespace Minivi
{
    class CarCallManager : public CarCallManagerBase
    {
    public:
        explicit CarCallManager(std::shared_ptr<IBtHfp> bthfp);
        ~CarCallManager() noexcept override;

    protected:
        void onInit(const std::function<void(serp::Service::Status)> reply) override;
        void onDeinit(const std::function<void(serp::Service::Status)> reply) override;

        void dial(serp::ResponsePtr<bool> reply, const std::string& number) override;
        void acceptCall(serp::ResponsePtr<bool> reply) override;
        void endCall(serp::ResponsePtr<bool> reply) override;
        void declineCall(serp::ResponsePtr<bool> reply) override;
        void muteCall(serp::ResponsePtr<bool> reply) override;
        void unmuteCall(serp::ResponsePtr<bool> reply) override;
        void sendDtmf(serp::ResponsePtr<bool> reply, const std::string& key) override;
        void getCallState(serp::ResponsePtr<CallState> reply) override;
        void frame(serp::ResponsePtr<std::string> reply) override;

    private:
        Minivi::CallDirection mDirection{Minivi::CallDirection::incoming};
        uint32_t mCallListSubId{0};
        uint32_t mConnStateSubId{0};
    };

} // namespace Minivi
