/*
 * This file was automatically generated by SERP generator on 2026-06-23.
 */

#include "CarCallManager.hpp"

#include "IBtHfp.hpp"

#include <sstream>
#include <vector>

namespace Minivi
{

namespace {

// Derive the single most significant call state from the active HFP call list.
// Priority: ringing/waiting > dialing/alerting > active/held > idle
struct CallSummary {
    CallState     state{CallState::idle};
    CallDirection direction{CallDirection::incoming};
    std::string   number;
};

CallSummary summarizeCalls(const std::vector<HfpCall>& calls)
{
    if (calls.empty()) return {};

    const HfpCall* primary = nullptr;
    CallState      mapped  = CallState::idle;

    for (const auto& c : calls) {
        if (c.status == HfpCallStatus::incoming || c.status == HfpCallStatus::waiting) {
            primary = &c; mapped = CallState::ringing; break;
        }
    }
    if (!primary) {
        for (const auto& c : calls) {
            if (c.status == HfpCallStatus::dialing || c.status == HfpCallStatus::alerting) {
                primary = &c; mapped = CallState::dialing; break;
            }
        }
    }
    if (!primary) {
        for (const auto& c : calls) {
            if (c.status == HfpCallStatus::active || c.status == HfpCallStatus::held) {
                primary = &c; mapped = CallState::active; break;
            }
        }
    }

    if (!primary) return {};

    const CallDirection dir = (primary->direction == HfpCallDirection::incoming)
        ? CallDirection::incoming
        : CallDirection::outgoing;

    return {mapped, dir, primary->number};
}

} // namespace

    std::shared_ptr<ICarCallManager> ICarCallManager::create(std::shared_ptr<IBtHfp> bthfp) {
        return std::make_shared<CarCallManager>(bthfp);
    }

    CarCallManager::CarCallManager(std::shared_ptr<IBtHfp> bthfp)
        : CarCallManagerBase(bthfp)
    {
        logMethod("CarCallManager");
        CurrentCallState.assignFromTransport(CallState::idle);
        CurrentCallDirection.assignFromTransport(Minivi::CallDirection::incoming);
        PhoneNumber.assignFromTransport(std::string{});
        ContactName.assignFromTransport(std::string{});
        MuteActive.assignFromTransport(false);
    }

    CarCallManager::~CarCallManager() noexcept
    {
        if (mCallListSubId && mBtHfp)
            mBtHfp->CallListChanged.disconnect(mCallListSubId);
        if (mConnStateSubId && mBtHfp)
            mBtHfp->ConnectionStateChanged.disconnect(mConnStateSubId);
    }

    void CarCallManager::onInit(const std::function<void(serp::Service::Status)> reply)
    {
        logInfo() << "onInit";

        mCallListSubId = mBtHfp->CallListChanged.connect(
            [this](const std::vector<HfpCall>& calls) {
                const auto s = summarizeCalls(calls);

                mDirection       = s.direction;
                CurrentCallState = s.state;
                CurrentCallDirection = mDirection;
                PhoneNumber      = s.number;
                ContactName      = s.number;
                MuteActive       = static_cast<bool>(mBtHfp->MicMuted);

                CallChanged(s.state, s.number, mDirection);
            });

        mConnStateSubId = mBtHfp->ConnectionStateChanged.connect(
            [this](BtConnectionState state, const std::string&) {
                if (state == BtConnectionState::disconnected) {
                    CurrentCallState = CallState::idle;
                    CurrentCallDirection = mDirection;
                    PhoneNumber      = "";
                    ContactName      = "";
                    CallChanged(CallState::idle, "", mDirection);
                }
            });

        reply(serp::Service::Status::SUCCESSFUL);
    }

    void CarCallManager::onDeinit(const std::function<void(serp::Service::Status)> reply)
    {
        logInfo() << "onDeinit";
        if (mCallListSubId) {
            mBtHfp->CallListChanged.disconnect(mCallListSubId);
            mCallListSubId = 0;
        }
        if (mConnStateSubId) {
            mBtHfp->ConnectionStateChanged.disconnect(mConnStateSubId);
            mConnStateSubId = 0;
        }
        reply(serp::Service::Status::SUCCESSFUL);
    }

    void CarCallManager::dial(serp::ResponsePtr<bool> reply, const std::string& number)
    {
        logInfo() << "dial number=" << number;
        // Optimistic update — mBtHfp will confirm the state via CallListChanged
        mDirection       = Minivi::CallDirection::outgoing;
        CurrentCallState = CallState::dialing;
        CurrentCallDirection = mDirection;
        PhoneNumber      = number;
        ContactName      = number;
        CallChanged(CallState::dialing, number, mDirection);

        mBtHfp->Dial(number);
        reply->call(true);
    }

    void CarCallManager::acceptCall(serp::ResponsePtr<bool> reply)
    {
        logInfo() << "acceptCall";
        mBtHfp->Answer();  // CallListChanged will update state to active
        reply->call(true);
    }

    void CarCallManager::endCall(serp::ResponsePtr<bool> reply)
    {
        logInfo() << "endCall";
        mBtHfp->Hangup();  // CallListChanged -> empty list -> idle
        reply->call(true);
    }

    void CarCallManager::declineCall(serp::ResponsePtr<bool> reply)
    {
        logInfo() << "declineCall";
        mBtHfp->Reject();  // CallListChanged will clear the incoming call
        reply->call(true);
    }

    void CarCallManager::muteCall(serp::ResponsePtr<bool> reply)
    {
        logInfo() << "muteCall";
        mBtHfp->SetMicMute(true);
        MuteActive = true;
        reply->call(true);
    }

    void CarCallManager::unmuteCall(serp::ResponsePtr<bool> reply)
    {
        logInfo() << "unmuteCall";
        mBtHfp->SetMicMute(false);
        MuteActive = false;
        reply->call(true);
    }

    void CarCallManager::sendDtmf(serp::ResponsePtr<bool> reply, const std::string& key)
    {
        logInfo() << "sendDtmf key=" << key;
        mBtHfp->SendDtmf(key);
        reply->call(true);
    }

    void CarCallManager::getCallState(serp::ResponsePtr<CallState> reply)
    {
        reply->call(static_cast<CallState>(CurrentCallState));
    }

    void CarCallManager::frame(serp::ResponsePtr<std::string> reply)
    {
        std::ostringstream out;
        out << "call.state="   << static_cast<CallState>(CurrentCallState) << "\n";
        out << "call.dir="     << mDirection << "\n";
        out << "call.number="  << static_cast<std::string>(PhoneNumber)    << "\n";
        out << "call.contact=" << static_cast<std::string>(ContactName)    << "\n";
        out << "call.mute="    << (static_cast<bool>(MuteActive) ? "true" : "false") << "\n";
        out << "bt.device="    << static_cast<std::string>(mBtHfp->DeviceName)        << "\n";
        out << "bt.conn="      << static_cast<BtConnectionState>(mBtHfp->ConnectionState) << "\n";
        reply->call(out.str());
    }

} // namespace Minivi
