/*
 * This file was automatically generated by SERP generator on 2026-06-12.
 */

#include "CarPhoneManager.hpp"

#include "IPhoneHal.hpp"
#include <sstream>

namespace Minivi
{
    std::shared_ptr<ICarPhoneManager> ICarPhoneManager::create(std::shared_ptr<IPhoneHal> phonehal) {
        return std::make_shared<CarPhoneManager>(phonehal);
    }

    CarPhoneManager::CarPhoneManager(std::shared_ptr<IPhoneHal> phonehal)
        : CarPhoneManagerBase(phonehal)
    {
        logMethod("CarPhoneManager");
        CurrentCallState.assignFromTransport(0);  // idle
        PhoneNumber.assignFromTransport(std::string{});
        ContactName.assignFromTransport(std::string{});
        Contacts.assignFromTransport(std::vector<std::string>{"Alice", "Bob", "Charlie", "Diana"});
    }

    CarPhoneManager::~CarPhoneManager() noexcept = default;

    void CarPhoneManager::onInit(const std::function<void(serp::Service::Status)> reply)
    {
        logInfo() << "onInit";
        CurrentCallState = static_cast<int32_t>(CurrentCallState);
        reply(serp::Service::Status::SUCCESSFUL);
    }

    void CarPhoneManager::onDeinit(const std::function<void(serp::Service::Status)> reply)
    {
        logInfo() << "onDeinit";
        reply(serp::Service::Status::SUCCESSFUL);
    }

    void CarPhoneManager::incoming(serp::ResponsePtr<bool> reply, const std::string& caller)
    {
        logInfo() << "incoming caller=" << caller;
        CurrentCallState = 1;  // ringing
        PhoneNumber      = caller;
        ContactName      = caller;
        CallChanged("ringing", caller);
        reply->call(true);
    }

    void CarPhoneManager::acceptCall(serp::ResponsePtr<bool> reply)
    {
        logInfo() << "acceptCall";
        CurrentCallState = 2;  // active
        CallChanged("active", static_cast<std::string>(PhoneNumber));
        reply->call(true);
    }

    void CarPhoneManager::endCall(serp::ResponsePtr<bool> reply)
    {
        logInfo() << "endCall";
        CurrentCallState = 0;  // idle
        PhoneNumber      = "";
        ContactName      = "";
        CallChanged("", "");
        reply->call(true);
    }

    void CarPhoneManager::dial(serp::ResponsePtr<bool> reply, const std::string& number)
    {
        logInfo() << "dial number=" << number;
        CurrentCallState = 1;  // ringing (outgoing)
        PhoneNumber      = number;
        ContactName      = number;
        CallChanged("ringing", number);
        reply->call(true);
    }

    void CarPhoneManager::callState(serp::ResponsePtr<std::string> reply)
    {
        const int32_t state = static_cast<int32_t>(CurrentCallState);
        const char* names[] = {"idle", "ringing", "active", "ended"};
        reply->call(state >= 0 && state < 4 ? names[state] : "idle");
    }

    void CarPhoneManager::callNumber(serp::ResponsePtr<std::string> reply)
    {
        reply->call(static_cast<std::string>(PhoneNumber));
    }

    void CarPhoneManager::frame(serp::ResponsePtr<std::string> reply)
    {
        std::ostringstream out;
        out << "phone.state="  << static_cast<int32_t>(CurrentCallState) << "\n";
        out << "phone.number=" << static_cast<std::string>(PhoneNumber)  << "\n";
        reply->call(out.str());
    }

} // namespace Minivi
