/*
 * This file was automatically generated by SERP generator on 2026-06-12.
 */

#pragma once

#include <functional>
#include <memory>
#include <tuple>

#include "CarPhoneManagerBase.hpp"

namespace Minivi
{
    class CarPhoneManager : public CarPhoneManagerBase
    {
    public:
        explicit CarPhoneManager(std::shared_ptr<IPhoneHal> phonehal);
        ~CarPhoneManager() noexcept override;

    protected:
        void onInit(const std::function<void(serp::Service::Status)> reply) override;
        void onDeinit(const std::function<void(serp::Service::Status)> reply) override;

        void incoming(serp::ResponsePtr<bool> reply, const std::string& caller) override;
        void acceptCall(serp::ResponsePtr<bool> reply) override;
        void endCall(serp::ResponsePtr<bool> reply) override;
        void dial(serp::ResponsePtr<bool> reply, const std::string& number) override;
        void callState(serp::ResponsePtr<std::string> reply) override;
        void callNumber(serp::ResponsePtr<std::string> reply) override;
        void frame(serp::ResponsePtr<std::string> reply) override;
    };

} // namespace Minivi
