/*
 * This file was automatically generated by SERP generator on 2026-06-23.
 */

#include "BtGateway.hpp"

#include <algorithm>
#include <cmath>
#include <map>
#include <mutex>
#include <sstream>
#include <vector>

namespace Minivi
{
    std::shared_ptr<IBtHfp> IBtHfp::create() {
        return std::make_shared<BtGateway>();
    }

    BtGateway::BtGateway()
        : BtGatewayBase()
    {
        logMethod("BtGateway");
    }

    BtGateway::~BtGateway() noexcept = default;

    void BtGateway::onInit(const std::function<void(serp::Service::Status)> reply)
    {
        logWarn() << "onInit is not implemented";
        reply(serp::Service::Status::SUCCESSFUL);
    }

    void BtGateway::onDeinit(const std::function<void(serp::Service::Status)> reply)
    {
        logWarn() << "onDeinit is not implemented";
        reply(serp::Service::Status::SUCCESSFUL);
    }

    void BtGateway::dial(serp::ResponsePtr<bool> reply, const std::string& number)
    {
        logWarn() << "dial is not implemented in product implementation";
        bool result{};
        reply->call(result);
    }

    void BtGateway::redial(serp::ResponsePtr<bool> reply)
    {
        logWarn() << "redial is not implemented in product implementation";
        bool result{};
        reply->call(result);
    }

    void BtGateway::answer(serp::ResponsePtr<bool> reply)
    {
        logWarn() << "answer is not implemented in product implementation";
        bool result{};
        reply->call(result);
    }

    void BtGateway::reject(serp::ResponsePtr<bool> reply)
    {
        logWarn() << "reject is not implemented in product implementation";
        bool result{};
        reply->call(result);
    }

    void BtGateway::hangup(serp::ResponsePtr<bool> reply)
    {
        logWarn() << "hangup is not implemented in product implementation";
        bool result{};
        reply->call(result);
    }

    void BtGateway::holdAndAnswer(serp::ResponsePtr<bool> reply)
    {
        logWarn() << "holdAndAnswer is not implemented in product implementation";
        bool result{};
        reply->call(result);
    }

    void BtGateway::releaseAndAnswer(serp::ResponsePtr<bool> reply)
    {
        logWarn() << "releaseAndAnswer is not implemented in product implementation";
        bool result{};
        reply->call(result);
    }

    void BtGateway::releaseAllHeld(serp::ResponsePtr<bool> reply)
    {
        logWarn() << "releaseAllHeld is not implemented in product implementation";
        bool result{};
        reply->call(result);
    }

    void BtGateway::sendDtmf(serp::ResponsePtr<bool> reply, const std::string& key)
    {
        logWarn() << "sendDtmf is not implemented in product implementation";
        bool result{};
        reply->call(result);
    }

    void BtGateway::setMicMute(serp::ResponsePtr<bool> reply, const bool& muted)
    {
        logWarn() << "setMicMute is not implemented in product implementation";
        bool result{};
        reply->call(result);
    }

    void BtGateway::setMicVolume(serp::ResponsePtr<bool> reply, const int32_t& level)
    {
        logWarn() << "setMicVolume is not implemented in product implementation";
        bool result{};
        reply->call(result);
    }

    void BtGateway::setSpeakerVolume(serp::ResponsePtr<bool> reply, const int32_t& level)
    {
        logWarn() << "setSpeakerVolume is not implemented in product implementation";
        bool result{};
        reply->call(result);
    }

    void BtGateway::connectAudio(serp::ResponsePtr<bool> reply)
    {
        logWarn() << "connectAudio is not implemented in product implementation";
        bool result{};
        reply->call(result);
    }

    void BtGateway::disconnectAudio(serp::ResponsePtr<bool> reply)
    {
        logWarn() << "disconnectAudio is not implemented in product implementation";
        bool result{};
        reply->call(result);
    }

    void BtGateway::pullPhoneBook(serp::ResponsePtr<bool> reply, const PbapFolder& folder)
    {
        logWarn() << "pullPhoneBook is not implemented in product implementation";
        bool result{};
        reply->call(result);
    }

    void BtGateway::pullCallHistory(serp::ResponsePtr<bool> reply, const CallHistoryType& type)
    {
        logWarn() << "pullCallHistory is not implemented in product implementation";
        bool result{};
        reply->call(result);
    }

    void BtGateway::cancelSync(serp::ResponsePtr<bool> reply)
    {
        logWarn() << "cancelSync is not implemented in product implementation";
        bool result{};
        reply->call(result);
    }

} // namespace Minivi
