/*
 * This file was automatically generated by SERP generator on 2026-06-23.
 */

#pragma once

#include <functional>
#include <memory>
#include <tuple>

#include "BtGatewayBase.hpp"

namespace Minivi
{
    class BtGateway : public BtGatewayBase
    {
    public:
        explicit BtGateway();
        ~BtGateway() noexcept override;

    protected:
        void onInit(const std::function<void(serp::Service::Status)> reply) override;
        void onDeinit(const std::function<void(serp::Service::Status)> reply) override;

        void dial(serp::ResponsePtr<bool> reply, const std::string& number) override;
        void redial(serp::ResponsePtr<bool> reply) override;
        void answer(serp::ResponsePtr<bool> reply) override;
        void reject(serp::ResponsePtr<bool> reply) override;
        void hangup(serp::ResponsePtr<bool> reply) override;
        void holdAndAnswer(serp::ResponsePtr<bool> reply) override;
        void releaseAndAnswer(serp::ResponsePtr<bool> reply) override;
        void releaseAllHeld(serp::ResponsePtr<bool> reply) override;
        void sendDtmf(serp::ResponsePtr<bool> reply, const std::string& key) override;
        void setMicMute(serp::ResponsePtr<bool> reply, const bool& muted) override;
        void setMicVolume(serp::ResponsePtr<bool> reply, const int32_t& level) override;
        void setSpeakerVolume(serp::ResponsePtr<bool> reply, const int32_t& level) override;
        void connectAudio(serp::ResponsePtr<bool> reply) override;
        void disconnectAudio(serp::ResponsePtr<bool> reply) override;
        void pullPhoneBook(serp::ResponsePtr<bool> reply, const PbapFolder& folder) override;
        void pullCallHistory(serp::ResponsePtr<bool> reply, const CallHistoryType& type) override;
        void cancelSync(serp::ResponsePtr<bool> reply) override;
    };

} // namespace Minivi
