/*
 * This file was automatically generated by SERP generator on 2026-06-12.
 */

#pragma once

#include <functional>
#include <memory>
#include <tuple>

#include "CarPropertyServiceBase.hpp"

namespace Minivi
{
    class CarPropertyService : public CarPropertyServiceBase
    {
    public:
        explicit CarPropertyService(std::shared_ptr<IVehicleHal> vehiclehal, std::shared_ptr<IPersistenceService> persistenceservice);
        ~CarPropertyService() noexcept override;

    protected:
        void onInit(const std::function<void(serp::Service::Status)> reply) override;
        void onDeinit(const std::function<void(serp::Service::Status)> reply) override;

        void setProperty(serp::ResponsePtr<bool> reply, const std::string& key, const std::string& value) override;
        void getProperty(serp::ResponsePtr<std::string> reply, const std::string& key) override;
        void subscribeProperty(serp::ResponsePtr<bool> reply, const std::string& key) override;
        void frame(serp::ResponsePtr<std::string> reply) override;
    };

} // namespace Minivi
