/*
 * This file was automatically generated by SERP generator on 2026-06-12.
 */

#include "CarPropertyService.hpp"

#include <sstream>
#include <stdexcept>

namespace Minivi
{
    std::shared_ptr<ICarPropertyService> ICarPropertyService::create(std::shared_ptr<IVehicleHal> vehiclehal, std::shared_ptr<IPersistenceService> persistenceservice) {
        return std::make_shared<CarPropertyService>(vehiclehal, persistenceservice);
    }

    CarPropertyService::CarPropertyService(std::shared_ptr<IVehicleHal> vehiclehal, std::shared_ptr<IPersistenceService> persistenceservice)
        : CarPropertyServiceBase(vehiclehal, persistenceservice)
    {
        logMethod("CarPropertyService");
        Ignition.assignFromTransport(false);
        Gear.assignFromTransport(std::string{"P"});
        Speed.assignFromTransport(0.0);
        Moving.assignFromTransport(false);
        Odometer.assignFromTransport(0.0);
        FuelLevel.assignFromTransport(0.75);
    }

    CarPropertyService::~CarPropertyService() noexcept = default;

    void CarPropertyService::onInit(const std::function<void(serp::Service::Status)> reply)
    {
        logInfo() << "onInit";
        Ignition  = static_cast<bool>(Ignition);
        Gear      = static_cast<std::string>(Gear);
        Speed     = static_cast<double>(Speed);
        Moving    = static_cast<bool>(Moving);
        Odometer  = static_cast<double>(Odometer);
        FuelLevel = static_cast<double>(FuelLevel);
        reply(serp::Service::Status::SUCCESSFUL);
    }

    void CarPropertyService::onDeinit(const std::function<void(serp::Service::Status)> reply)
    {
        logInfo() << "onDeinit";
        reply(serp::Service::Status::SUCCESSFUL);
    }

    void CarPropertyService::setProperty(serp::ResponsePtr<bool> reply, const std::string& key, const std::string& value)
    {
        logInfo() << "setProperty " << key << "=" << value;
        try {
            if (key == "ignition")  { Ignition = (value == "true" || value == "1" || value == "on"); VehiclePropertyChanged(key, value); }
            else if (key == "gear") { Gear     = value;                     VehiclePropertyChanged(key, value); }
            else if (key == "speed") { Speed   = std::stod(value);          VehiclePropertyChanged(key, value); }
            else if (key == "moving") { Moving = (value == "true" || value == "1"); VehiclePropertyChanged(key, value); }
            else if (key == "odometer") { Odometer  = std::stod(value);     VehiclePropertyChanged(key, value); }
            else if (key == "fuelLevel") { FuelLevel = std::stod(value);    VehiclePropertyChanged(key, value); }
            else { logWarn() << "CarPropertyService::setProperty unknown key: " << key; }
        } catch (...) {
            logWarn() << "CarPropertyService::setProperty parse error key=" << key << " value=" << value;
        }
        reply->call(true);
    }

    void CarPropertyService::getProperty(serp::ResponsePtr<std::string> reply, const std::string& key)
    {
        if      (key == "ignition")  reply->call(static_cast<bool>(Ignition) ? "true" : "false");
        else if (key == "gear")      reply->call(static_cast<std::string>(Gear));
        else if (key == "speed")     reply->call(std::to_string(static_cast<double>(Speed)));
        else if (key == "moving")    reply->call(static_cast<bool>(Moving) ? "true" : "false");
        else if (key == "odometer")  reply->call(std::to_string(static_cast<double>(Odometer)));
        else if (key == "fuelLevel") reply->call(std::to_string(static_cast<double>(FuelLevel)));
        else                         reply->call("");
    }

    void CarPropertyService::subscribeProperty(serp::ResponsePtr<bool> reply, const std::string& key)
    {
        logInfo() << "subscribeProperty key=" << key;
        reply->call(true);
    }

    void CarPropertyService::frame(serp::ResponsePtr<std::string> reply)
    {
        std::ostringstream out;
        out << "vehicle.ignition=" << (static_cast<bool>(Ignition) ? "true" : "false") << "\n";
        out << "vehicle.gear="     << static_cast<std::string>(Gear) << "\n";
        out << "vehicle.speed="    << static_cast<double>(Speed)     << "\n";
        out << "vehicle.moving="   << (static_cast<bool>(Moving) ? "true" : "false") << "\n";
        out << "vehicle.odometer=" << static_cast<double>(Odometer)  << "\n";
        out << "vehicle.fuel="     << static_cast<double>(FuelLevel) << "\n";
        reply->call(out.str());
    }

} // namespace Minivi
