/*
 * This file was automatically generated by SERP generator on 2026-06-23.
 */

#include "CarContactsManager.hpp"

#include "IBtPbap.hpp"
#include "IPersistenceService.hpp"

#include <algorithm>
#include <cctype>
#include <sstream>
#include <vector>

namespace Minivi
{
    std::shared_ptr<ICarContactsManager> ICarContactsManager::create(std::shared_ptr<IBtPbap> btpbap, std::shared_ptr<IPersistenceService> persistenceservice) {
        return std::make_shared<CarContactsManager>(btpbap, persistenceservice);
    }

    CarContactsManager::CarContactsManager(std::shared_ptr<IBtPbap> btpbap, std::shared_ptr<IPersistenceService> persistenceservice)
        : CarContactsManagerBase(btpbap, persistenceservice)
    {
        logMethod("CarContactsManager");
    }

    CarContactsManager::~CarContactsManager() noexcept = default;

    void CarContactsManager::onInit(const std::function<void(serp::Service::Status)> reply)
    {
        logInfo() << "onInit";

        // Use contacts already cached in the HAL (e.g. reconnect after crash)
        const auto cached = static_cast<std::vector<Contact>>(mBtPbap->Contacts);
        if (!cached.empty()) {
            Contacts = cached;
        }

        // ContactsReady fires when a PBAP phonebook pull completes
        mContactsReadySubId = mBtPbap->ContactsReady.connect([this](const std::vector<Contact>& contacts) {
            logInfo() << "ContactsReady count=" << contacts.size();
            Contacts = contacts;
            applyDialFilter();
            applySearchFilter();
        });

        // CallHistoryReady fires when a PBAP call-history pull completes
        mCallHistoryReadySubId = mBtPbap->CallHistoryReady.connect([this](const std::vector<CallRecord>& records) {
            logInfo() << "CallHistoryReady count=" << records.size();
            RecentCalls = records;
        });

        // Restore persisted favorites (user-curated, not from PBAP)
        auto favP = mPersistenceService->GetValue("contacts.favorites");
        if (favP) {
            favP->subscribe([this](int32_t, const std::string& data) {
                if (!data.empty()) FavoriteContacts = parseFavorites(data);
            });
        }

        // Kick off BT phonebook and call-history sync
        mBtPbap->PullPhoneBook(PbapFolder::phoneBook);
        mBtPbap->PullCallHistory(CallHistoryType::combined);

        reply(serp::Service::Status::SUCCESSFUL);
    }

    void CarContactsManager::onDeinit(const std::function<void(serp::Service::Status)> reply)
    {
        logInfo() << "onDeinit";
        if (mContactsReadySubId)    { mBtPbap->ContactsReady.disconnect(mContactsReadySubId);      mContactsReadySubId = 0; }
        if (mCallHistoryReadySubId) { mBtPbap->CallHistoryReady.disconnect(mCallHistoryReadySubId); mCallHistoryReadySubId = 0; }
        reply(serp::Service::Status::SUCCESSFUL);
    }

    void CarContactsManager::setDialQuery(serp::ResponsePtr<bool> reply, const std::string& query)
    {
        logInfo() << "setDialQuery query=" << query;
        DialQuery = query;
        applyDialFilter();
        reply->call(true);
    }

    void CarContactsManager::setContactSearchQuery(serp::ResponsePtr<bool> reply, const std::string& query)
    {
        logInfo() << "setContactSearchQuery query=" << query;
        ContactSearchQuery = query;
        applySearchFilter();
        reply->call(true);
    }

    // ── Private helpers ────────────────────────────────────────────────────────

    void CarContactsManager::applyDialFilter()
    {
        const std::string query = static_cast<std::string>(DialQuery);
        if (query.empty()) {
            DialFilteredContacts = {};
            return;
        }
        std::vector<Contact> result;
        for (const auto& c : static_cast<std::vector<Contact>>(Contacts)) {
            if (c.number.rfind(query, 0) == 0) result.push_back(c);  // number-prefix match
        }
        DialFilteredContacts = result;
    }

    void CarContactsManager::applySearchFilter()
    {
        const std::string query = static_cast<std::string>(ContactSearchQuery);
        if (query.empty()) {
            ContactSearchResults = {};
            return;
        }
        std::string lq = query;
        std::transform(lq.begin(), lq.end(), lq.begin(),
                       [](unsigned char c){ return std::tolower(c); });

        std::vector<Contact> result;
        for (const auto& c : static_cast<std::vector<Contact>>(Contacts)) {
            std::string ln = c.name, lnum = c.number;
            std::transform(ln.begin(),   ln.end(),   ln.begin(),   [](unsigned char x){ return std::tolower(x); });
            std::transform(lnum.begin(), lnum.end(), lnum.begin(), [](unsigned char x){ return std::tolower(x); });
            if (ln.find(lq) != std::string::npos || lnum.find(lq) != std::string::npos)
                result.push_back(c);
        }
        ContactSearchResults = result;
    }

    void CarContactsManager::persistFavorites()
    {
        mPersistenceService->SetValue("contacts.favorites",
                                      serializeFavorites(static_cast<std::vector<Contact>>(FavoriteContacts)));
    }

    // ── Serialization ──────────────────────────────────────────────────────────
    // Format: ';'-separated records, '|'-separated fields

    std::vector<Contact> CarContactsManager::parseFavorites(const std::string& data)
    {
        std::vector<Contact> result;
        std::istringstream rs(data);
        std::string rec;
        while (std::getline(rs, rec, ';')) {
            if (rec.empty()) continue;
            const auto sep = rec.find('|');
            if (sep == std::string::npos) continue;
            result.push_back({rec.substr(0, sep), rec.substr(sep + 1)});
        }
        return result;
    }

    std::string CarContactsManager::serializeFavorites(const std::vector<Contact>& contacts)
    {
        std::ostringstream out;
        for (const auto& c : contacts) out << c.name << '|' << c.number << ';';
        return out.str();
    }

} // namespace Minivi
