/*
 * This file was automatically generated by SERP generator on 2026-06-23.
 */

#pragma once

#include <functional>
#include <memory>
#include <tuple>

#include "CarContactsManagerBase.hpp"

namespace Minivi
{
    class CarContactsManager : public CarContactsManagerBase
    {
    public:
        explicit CarContactsManager(std::shared_ptr<IBtPbap> btpbap, std::shared_ptr<IPersistenceService> persistenceservice);
        ~CarContactsManager() noexcept override;

    protected:
        void onInit(const std::function<void(serp::Service::Status)> reply) override;
        void onDeinit(const std::function<void(serp::Service::Status)> reply) override;

        void setDialQuery(serp::ResponsePtr<bool> reply, const std::string& query) override;
        void setContactSearchQuery(serp::ResponsePtr<bool> reply, const std::string& query) override;

    private:
        void applyDialFilter();
        void applySearchFilter();
        void persistFavorites();
        static std::vector<Contact> parseFavorites(const std::string& data);
        static std::string serializeFavorites(const std::vector<Contact>& contacts);

        uint32_t mContactsReadySubId{};
        uint32_t mCallHistoryReadySubId{};
    };

} // namespace Minivi
