/*
 * This file was automatically generated by SERP generator on 2026-06-12.
 */

#pragma once

#include <functional>
#include <memory>
#include <tuple>

#include "CarRadioManagerBase.hpp"

namespace Minivi
{
    class CarRadioManager : public CarRadioManagerBase
    {
    public:
        explicit CarRadioManager(std::shared_ptr<ICarAudioManager> caraudiomanager, std::shared_ptr<IRadioHal> radiohal, std::shared_ptr<IPersistenceService> persistenceservice);
        ~CarRadioManager() noexcept override;

    protected:
        void onInit(const std::function<void(serp::Service::Status)> reply) override;
        void onDeinit(const std::function<void(serp::Service::Status)> reply) override;

        void tune(serp::ResponsePtr<bool> reply, const std::string& frequency) override;
        void seek(serp::ResponsePtr<bool> reply, const SeekDirection& direction) override;
        void tunerStation(serp::ResponsePtr<std::string> reply) override;
        void frame(serp::ResponsePtr<std::string> reply) override;
    };

} // namespace Minivi
