/*
 * This file was automatically generated by SERP generator on 2026-06-12.
 */

#include "CarRadioManager.hpp"

#include "IRadioHal.hpp"
#include "IPersistenceService.hpp"

#include <algorithm>
#include <sstream>
#include <vector>

namespace Minivi
{

namespace {

// Station presets — must match RadioHal kStations keys
static const std::vector<std::string> kPresets = {
    "87.5", "98.7", "101.1", "103.7", "107.9", "AM:612"
};

static const std::string kDefaultFm = "87.5";
static const std::string kDefaultAm = "AM:612";

// Station metadata replicated from RadioHal — authoritative names live in RadioHal/BT stack.
// In production this would be populated via RDS data or BT HFP response.
static const std::map<std::string, std::pair<std::string, std::string>> kStationMeta = {
    {"87.5",   {"FM", "Groove Salad"}},
    {"98.7",   {"FM", "Secret Agent"}},
    {"101.1",  {"FM", "Indie Pop Rocks"}},
    {"103.7",  {"FM", "Beat Blender"}},
    {"107.9",  {"FM", "Mission Control"}},
    {"AM:612", {"AM", "The Trip"}},
};

static std::pair<std::string, std::string> stationMeta(const std::string& freq) {
    const auto it = kStationMeta.find(freq);
    return it != kStationMeta.end() ? it->second : std::make_pair(std::string("FM"), freq);
}

} // namespace

    std::shared_ptr<ICarRadioManager> ICarRadioManager::create(std::shared_ptr<ICarAudioManager> caraudiomanager, std::shared_ptr<IRadioHal> radiohal, std::shared_ptr<IPersistenceService> persistenceservice) {
        return std::make_shared<CarRadioManager>(caraudiomanager, radiohal, persistenceservice);
    }

    CarRadioManager::CarRadioManager(std::shared_ptr<ICarAudioManager> caraudiomanager, std::shared_ptr<IRadioHal> radiohal, std::shared_ptr<IPersistenceService> persistenceservice)
        : CarRadioManagerBase(caraudiomanager, radiohal, persistenceservice)
    {
        logMethod("CarRadioManager");
        Station.assignFromTransport(kDefaultFm);
        const auto [band, name] = stationMeta(kDefaultFm);
        Name.assignFromTransport(name);
        Signal.assignFromTransport(0);
    }

    CarRadioManager::~CarRadioManager() noexcept = default;

    void CarRadioManager::onInit(const std::function<void(serp::Service::Status)> reply)
    {
        logInfo() << "onInit";
        Station = static_cast<std::string>(Station);
        Name    = static_cast<std::string>(Name);
        Signal  = static_cast<int32_t>(Signal);
        reply(serp::Service::Status::SUCCESSFUL);
    }

    void CarRadioManager::onDeinit(const std::function<void(serp::Service::Status)> reply)
    {
        logInfo() << "onDeinit";
        reply(serp::Service::Status::SUCCESSFUL);
    }

    void CarRadioManager::tune(serp::ResponsePtr<bool> reply, const std::string& frequency)
    {
        logInfo() << "tune freq=" << frequency;

        if (frequency == "stop") {
            mRadioHal->Tune("stop");
            // Keep Station so the HMI PLAY button can restore the last station.
            // Signal=0 is the authoritative "not playing" indicator (snapshot uses signal>0).
            Name   = "";
            Signal = 0;
            TunerChanged("", TunerEvent::stopped);
            reply->call(true);
            return;
        }
        if (frequency == "FM") {
            const auto [fmBand, fmName] = stationMeta(kDefaultFm);
            Station = kDefaultFm;
            Name    = fmName;
            Signal  = 85;
            TunerChanged(kDefaultFm, TunerEvent::bandFm);
            mRadioHal->Tune(kDefaultFm);
            reply->call(true);
            return;
        }
        if (frequency == "AM") {
            const auto [amBand, amName] = stationMeta(kDefaultAm);
            Station = kDefaultAm;
            Name    = amName;
            Signal  = 85;
            TunerChanged(kDefaultAm, TunerEvent::bandAm);
            mRadioHal->Tune(kDefaultAm);
            reply->call(true);
            return;
        }

        const auto [band, name] = stationMeta(frequency);
        Station = frequency;
        Name    = name;
        Signal  = 85;
        TunerChanged(frequency, TunerEvent::tuned);
        mRadioHal->Tune(frequency);
        reply->call(true);
    }

    void CarRadioManager::seek(serp::ResponsePtr<bool> reply, const SeekDirection& direction)
    {
        logInfo() << "seek dir=" << direction;
        const std::string current = static_cast<std::string>(Station);
        const auto it = std::find(kPresets.begin(), kPresets.end(), current);
        std::string next;
        if (it == kPresets.end()) {
            next = kPresets.front();
        } else if (direction == SeekDirection::up) {
            const auto nit = std::next(it);
            next = (nit == kPresets.end()) ? kPresets.front() : *nit;
        } else {
            next = (it == kPresets.begin()) ? kPresets.back() : *std::prev(it);
        }
        const auto [band, name] = stationMeta(next);
        Station = next;
        Name    = name;
        Signal  = 85;
        TunerChanged(next, TunerEvent::seek);
        mRadioHal->Tune(next);
        reply->call(true);
    }

    void CarRadioManager::tunerStation(serp::ResponsePtr<std::string> reply)
    {
        reply->call(static_cast<std::string>(Station));
    }

    void CarRadioManager::frame(serp::ResponsePtr<std::string> reply)
    {
        std::ostringstream out;
        out << "radio.station=" << static_cast<std::string>(Station) << "\n";
        reply->call(out.str());
    }

} // namespace Minivi
