/*
 * This file was automatically generated by SERP generator on 2026-06-12.
 */

#include "CarNotificationManager.hpp"

#include <algorithm>
#include <sstream>

namespace Minivi
{
    std::shared_ptr<ICarNotificationManager> ICarNotificationManager::create(std::shared_ptr<IPersistenceService> persistenceservice) {
        return std::make_shared<CarNotificationManager>(persistenceservice);
    }

    CarNotificationManager::CarNotificationManager(std::shared_ptr<IPersistenceService> persistenceservice)
        : CarNotificationManagerBase(persistenceservice)
    {
        logMethod("CarNotificationManager");
        UnreadCount.assignFromTransport(0);
        Notifications.assignFromTransport(std::vector<CarNotification>{});
    }

    CarNotificationManager::~CarNotificationManager() noexcept = default;

    void CarNotificationManager::onInit(const std::function<void(serp::Service::Status)> reply)
    {
        logInfo() << "onInit";
        UnreadCount = static_cast<int32_t>(UnreadCount);
        reply(serp::Service::Status::SUCCESSFUL);
    }

    void CarNotificationManager::onDeinit(const std::function<void(serp::Service::Status)> reply)
    {
        logInfo() << "onDeinit";
        mNotifications.clear();
        reply(serp::Service::Status::SUCCESSFUL);
    }

    void CarNotificationManager::post(serp::ResponsePtr<int32_t> reply, const std::string& target, const NotificationPriority& priority, const std::string& text)
    {
        logInfo() << "post target=" << target << " text=" << text;
        const int32_t id = mNextId++;
        const CarNotification n{id, text, target, priority};
        mNotifications.push_back(n);
        UnreadCount   = static_cast<int32_t>(mNotifications.size());
        Notifications = mNotifications;
        NotificationPosted(n);
        reply->call(id);
    }

    void CarNotificationManager::listAll(serp::ResponsePtr<std::vector<CarNotification>> reply)
    {
        reply->call(mNotifications);
    }

    void CarNotificationManager::dismiss(serp::ResponsePtr<bool> reply, const int32_t& id)
    {
        logInfo() << "dismiss id=" << id;
        const auto it = std::find_if(mNotifications.begin(), mNotifications.end(),
            [id](const CarNotification& n) { return n.id == id; });
        if (it != mNotifications.end()) {
            mNotifications.erase(it);
            UnreadCount   = static_cast<int32_t>(mNotifications.size());
            Notifications = mNotifications;
            NotificationDismissed(id);
            reply->call(true);
        } else {
            reply->call(false);
        }
    }

    void CarNotificationManager::dismissAll(serp::ResponsePtr<bool> reply)
    {
        logInfo() << "dismissAll";
        mNotifications.clear();
        UnreadCount   = 0;
        Notifications = mNotifications;
        reply->call(true);
    }

    void CarNotificationManager::markRead(serp::ResponsePtr<bool> reply, const int32_t& id)
    {
        logInfo() << "markRead id=" << id;
        reply->call(true);
    }

} // namespace Minivi
