/*
 * This file was automatically generated by SERP generator on 2026-06-12.
 */

#pragma once

#include <functional>
#include <memory>
#include <tuple>
#include <vector>

#include "CarNotificationManagerBase.hpp"

namespace Minivi
{
    class CarNotificationManager : public CarNotificationManagerBase
    {
    public:
        explicit CarNotificationManager(std::shared_ptr<IPersistenceService> persistenceservice);
        ~CarNotificationManager() noexcept override;

    protected:
        void onInit(const std::function<void(serp::Service::Status)> reply) override;
        void onDeinit(const std::function<void(serp::Service::Status)> reply) override;

        void post(serp::ResponsePtr<int32_t> reply, const std::string& target, const NotificationPriority& priority, const std::string& text) override;
        void listAll(serp::ResponsePtr<std::vector<CarNotification>> reply) override;
        void dismiss(serp::ResponsePtr<bool> reply, const int32_t& id) override;
        void dismissAll(serp::ResponsePtr<bool> reply) override;
        void markRead(serp::ResponsePtr<bool> reply, const int32_t& id) override;

    private:
        int32_t mNextId{1};
        std::vector<CarNotification> mNotifications;
    };

} // namespace Minivi
