/*
 * This file was automatically generated by SERP generator on 2026-06-12.
 */

#pragma once

#include <functional>
#include <memory>
#include <tuple>

#include "CarClimateManagerBase.hpp"

namespace Minivi
{
    class CarClimateManager : public CarClimateManagerBase
    {
    public:
        explicit CarClimateManager(std::shared_ptr<IClimateHal> climatehal);
        ~CarClimateManager() noexcept override;

    protected:
        void onInit(const std::function<void(serp::Service::Status)> reply) override;
        void onDeinit(const std::function<void(serp::Service::Status)> reply) override;

        void setTemperature(serp::ResponsePtr<bool> reply, const std::string& zone, const double& temp) override;
        void setDriverTemp(serp::ResponsePtr<bool> reply, const double& temp) override;
        void setPassengerTemp(serp::ResponsePtr<bool> reply, const double& temp) override;
        void setFan(serp::ResponsePtr<bool> reply, const int32_t& fan) override;
        void setFanSpeed(serp::ResponsePtr<bool> reply, const int32_t& speed) override;
        void toggleAc(serp::ResponsePtr<bool> reply) override;
        void toggleSync(serp::ResponsePtr<bool> reply) override;
        void toggleAuto(serp::ResponsePtr<bool> reply) override;
        void toggleFrontDefrost(serp::ResponsePtr<bool> reply) override;
        void toggleRearDefrost(serp::ResponsePtr<bool> reply) override;
        void applyProfile(serp::ResponsePtr<bool> reply, const std::string& profile) override;
        void hvacDriverTemperature(serp::ResponsePtr<std::string> reply) override;
        void hvacPassengerTemperature(serp::ResponsePtr<std::string> reply) override;
        void hvacFan(serp::ResponsePtr<std::string> reply) override;
        void frame(serp::ResponsePtr<std::string> reply) override;
    };

} // namespace Minivi
