/*
 * This file was automatically generated by SERP generator on 2026-06-12.
 */

#include "CarClimateManager.hpp"

#include <sstream>

namespace Minivi
{
    std::shared_ptr<ICarClimateManager> ICarClimateManager::create(std::shared_ptr<IClimateHal> climatehal) {
        return std::make_shared<CarClimateManager>(climatehal);
    }

    CarClimateManager::CarClimateManager(std::shared_ptr<IClimateHal> climatehal)
        : CarClimateManagerBase(climatehal)
    {
        logMethod("CarClimateManager");
        DriverTemp.assignFromTransport(22.0);
        PassengerTemp.assignFromTransport(22.0);
        FanSpeed.assignFromTransport(2);
        AcOn.assignFromTransport(false);
        SyncOn.assignFromTransport(false);
        AutoOn.assignFromTransport(false);
        FrontDefrost.assignFromTransport(false);
        RearDefrost.assignFromTransport(false);
    }

    CarClimateManager::~CarClimateManager() noexcept = default;

    void CarClimateManager::onInit(const std::function<void(serp::Service::Status)> reply)
    {
        logInfo() << "onInit";
        DriverTemp    = static_cast<double>(DriverTemp);
        PassengerTemp = static_cast<double>(PassengerTemp);
        FanSpeed      = static_cast<int32_t>(FanSpeed);
        AcOn          = static_cast<bool>(AcOn);
        SyncOn        = static_cast<bool>(SyncOn);
        AutoOn        = static_cast<bool>(AutoOn);
        FrontDefrost  = static_cast<bool>(FrontDefrost);
        RearDefrost   = static_cast<bool>(RearDefrost);
        reply(serp::Service::Status::SUCCESSFUL);
    }

    void CarClimateManager::onDeinit(const std::function<void(serp::Service::Status)> reply)
    {
        logInfo() << "onDeinit";
        reply(serp::Service::Status::SUCCESSFUL);
    }

    void CarClimateManager::setTemperature(serp::ResponsePtr<bool> reply, const std::string& zone, const double& temp)
    {
        logInfo() << "setTemperature zone=" << zone << " temp=" << temp;
        if (zone == "driver" || zone == "all") {
            DriverTemp = temp;
        }
        if (zone == "passenger" || zone == "all") {
            PassengerTemp = temp;
        }
        HvacChanged(zone, std::to_string(temp), std::to_string(static_cast<int32_t>(FanSpeed)));
        reply->call(true);
    }

    void CarClimateManager::setDriverTemp(serp::ResponsePtr<bool> reply, const double& temp)
    {
        logInfo() << "setDriverTemp temp=" << temp;
        DriverTemp = temp;
        HvacChanged("driver", std::to_string(temp), std::to_string(static_cast<int32_t>(FanSpeed)));
        reply->call(true);
    }

    void CarClimateManager::setPassengerTemp(serp::ResponsePtr<bool> reply, const double& temp)
    {
        logInfo() << "setPassengerTemp temp=" << temp;
        PassengerTemp = temp;
        HvacChanged("passenger", std::to_string(temp), std::to_string(static_cast<int32_t>(FanSpeed)));
        reply->call(true);
    }

    void CarClimateManager::setFan(serp::ResponsePtr<bool> reply, const int32_t& fan)
    {
        logInfo() << "setFan level=" << fan;
        FanSpeed = fan;
        reply->call(true);
    }

    void CarClimateManager::setFanSpeed(serp::ResponsePtr<bool> reply, const int32_t& speed)
    {
        logInfo() << "setFanSpeed speed=" << speed;
        FanSpeed = speed;
        reply->call(true);
    }

    void CarClimateManager::toggleAc(serp::ResponsePtr<bool> reply)
    {
        logInfo() << "toggleAc";
        AcOn = !static_cast<bool>(AcOn);
        reply->call(true);
    }

    void CarClimateManager::toggleSync(serp::ResponsePtr<bool> reply)
    {
        logInfo() << "toggleSync";
        SyncOn = !static_cast<bool>(SyncOn);
        reply->call(true);
    }

    void CarClimateManager::toggleAuto(serp::ResponsePtr<bool> reply)
    {
        logInfo() << "toggleAuto";
        AutoOn = !static_cast<bool>(AutoOn);
        reply->call(true);
    }

    void CarClimateManager::toggleFrontDefrost(serp::ResponsePtr<bool> reply)
    {
        logInfo() << "toggleFrontDefrost";
        FrontDefrost = !static_cast<bool>(FrontDefrost);
        reply->call(true);
    }

    void CarClimateManager::toggleRearDefrost(serp::ResponsePtr<bool> reply)
    {
        logInfo() << "toggleRearDefrost";
        RearDefrost = !static_cast<bool>(RearDefrost);
        reply->call(true);
    }

    void CarClimateManager::applyProfile(serp::ResponsePtr<bool> reply, const std::string& profile)
    {
        logInfo() << "applyProfile profile=" << profile;
        reply->call(true);
    }

    void CarClimateManager::hvacDriverTemperature(serp::ResponsePtr<std::string> reply)
    {
        reply->call(std::to_string(static_cast<double>(DriverTemp)));
    }

    void CarClimateManager::hvacPassengerTemperature(serp::ResponsePtr<std::string> reply)
    {
        reply->call(std::to_string(static_cast<double>(PassengerTemp)));
    }

    void CarClimateManager::hvacFan(serp::ResponsePtr<std::string> reply)
    {
        reply->call(std::to_string(static_cast<int32_t>(FanSpeed)));
    }

    void CarClimateManager::frame(serp::ResponsePtr<std::string> reply)
    {
        std::ostringstream out;
        out << "climate.driver="    << static_cast<double>(DriverTemp)    << "\n";
        out << "climate.passenger=" << static_cast<double>(PassengerTemp) << "\n";
        out << "climate.fan="       << static_cast<int32_t>(FanSpeed)     << "\n";
        out << "climate.ac="        << static_cast<bool>(AcOn)            << "\n";
        reply->call(out.str());
    }

} // namespace Minivi
